name = "LuymaraMC"
author = "Luymara"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2727004073becbe604443ed1317a663ac261e0ce1707808e2d6be2ea060ba62d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
