name = "LuymaraMC"
author = "Luymara"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44778951adc7188fe111403ef9e712635b187062efef2170988f5a82eba8d2f6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
